export { cn } from "./lib/utils"
export { ThemeProvider, useTheme } from "./lib/theme"
export { Button, buttonVariants } from "./components/button/Button"
export { Badge, badgeVariants } from "./components/badge/Badge"
export { Avatar, AvatarImage, AvatarFallback } from "./components/avatar/Avatar"
export { AvatarDropdown } from "./components/avatar/AvatarDropdown"
export type { AvatarDropdownProps, AvatarDropdownUser, UserRole, AvatarDropdownMenuItem } from "./components/avatar/AvatarDropdown"
export { SearchBar } from "./components/searchbar/SearchBar"
export { SearchResults } from "./components/searchresults/SearchResults"
export { ProviderCard } from "./components/providercard/ProviderCard"
export { AppShell } from "./components/appshell/AppShell"
export type { AppShellProps } from "./components/appshell/AppShell"
export { NotificationDropdown } from "./components/notifications/NotificationDropdown"
export type { NotificationDropdownProps, Notification } from "./components/notifications/NotificationDropdown"
export { NotificationItem } from "./components/notifications/NotificationItem"
export type { NotificationItemProps } from "./components/notifications/NotificationItem"
export { NotificationBell } from "./components/notifications/NotificationBell"
export type { NotificationBellProps } from "./components/notifications/NotificationBell"
export { ChatDrawer } from "./components/chat/ChatDrawer"
export type { ChatDrawerProps, Conversation } from "./components/chat/ChatDrawer"

// Copilot
export { CopilotBubble } from "./components/copilot/CopilotBubble"
export { CopilotPanel } from "./components/copilot/CopilotPanel"
export { ModeSelector } from "./components/copilot/ModeSelector"
export type { CopilotMode } from "./components/copilot/ModeSelector"
export { ChatMessage } from "./components/copilot/ChatMessage"
export type { ChatMessageProps } from "./components/copilot/ChatMessage"
export { SuggestionChips } from "./components/copilot/SuggestionChips"
export { ThinkingIndicator } from "./components/copilot/ThinkingIndicator"
export { ConversationList } from "./components/chat/ConversationList"
export type { ConversationListProps } from "./components/chat/ConversationList"
export { MessageBubble } from "./components/chat/MessageBubble"
export type { MessageBubbleProps } from "./components/chat/MessageBubble"
export { MessageInput } from "./components/chat/MessageInput"
export type { MessageInputProps } from "./components/chat/MessageInput"
export { ChatThread } from "./components/chat/ChatThread"
export type { ChatThreadProps } from "./components/chat/ChatThread"
export { Sidebar } from "./components/sidebar/Sidebar"
export type { SidebarProps, SidebarNavItem } from "./components/sidebar/Sidebar"
export { BlockEditor, SectionCanvas, PalettePicker, TemplateGallery, FontPairPicker, SectionToolbar, BlockProperties } from "./components/builder"
export type { Block } from "./components/builder"
