export type Density = 'compact' | 'comfortable' | 'spacious'

export interface DensityConfig {
  padding: string
  heroHeight: string
  cardGap: string
  cardPadding: string
  fontSize: string
  sectionGap: string
}

export const DENSITY_CONFIGS: Record<Density, DensityConfig> = {
  compact: {
    padding: 'px-4 py-12 md:px-6 md:py-16',
    heroHeight: 'min-h-[40vh] md:min-h-[50vh]',
    cardGap: 'gap-3 md:gap-4',
    cardPadding: 'p-4',
    fontSize: 'text-sm md:text-base',
    sectionGap: 'space-y-8 md:space-y-12',
  },
  comfortable: {
    padding: 'px-6 py-16 md:px-8 md:py-20',
    heroHeight: 'min-h-[50vh] md:min-h-[65vh]',
    cardGap: 'gap-4 md:gap-6',
    cardPadding: 'p-6',
    fontSize: 'text-base md:text-lg',
    sectionGap: 'space-y-12 md:space-y-16',
  },
  spacious: {
    padding: 'px-8 py-20 md:px-12 md:py-28',
    heroHeight: 'min-h-[60vh] md:min-h-[80vh]',
    cardGap: 'gap-6 md:gap-8',
    cardPadding: 'p-8',
    fontSize: 'text-lg md:text-xl',
    sectionGap: 'space-y-16 md:space-y-24',
  },
}

export type TemplateCategory = 'universal' | 'hospitality' | 'beauty' | 'food' | 'music' | 'photography' | 'fitness' | 'events' | 'consulting'

export interface TemplateConfig {
  id: string
  name: string
  category: TemplateCategory
  description: string
  heroLayout: 'center' | 'left' | 'right' | 'split' | 'fullscreen' | 'minimal'
  navStyle: 'default' | 'glass' | 'minimal' | 'hamburger' | 'transparent'
  cardStyle: 'default' | 'glass' | 'bordered' | 'elevated' | 'minimal'
  borderRadius: 'none' | 'sm' | 'md' | 'lg' | 'xl' | 'full'
  sections: string[]
  thumbnail?: string
}

export const TEMPLATES: TemplateConfig[] = [
  // ============== UNIVERSAL ==============
  {
    id: 'aurora-hero',
    name: 'Aurora Hero',
    category: 'universal',
    description: 'Full-screen hero with gradient aurora effect and animated particles',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'glass',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'glass-stack',
    name: 'Glass Stack',
    category: 'universal',
    description: 'Glass-morphism layered cards with frosted backdrop',
    heroLayout: 'center',
    navStyle: 'glass',
    cardStyle: 'glass',
    borderRadius: 'xl',
    sections: ['hero', 'about', 'services', 'contact'],
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial Magazine',
    category: 'universal',
    description: 'Clean editorial layout with large typography and white space',
    heroLayout: 'left',
    navStyle: 'minimal',
    cardStyle: 'minimal',
    borderRadius: 'none',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'scroll-reveal',
    name: 'Scroll Reveal',
    category: 'universal',
    description: 'Sections animate on scroll with staggered reveals',
    heroLayout: 'split',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'gallery', 'contact', 'testimonials'],
  },
  {
    id: 'bento-grid',
    name: 'Bento Grid',
    category: 'universal',
    description: 'Modern bento-box grid layout with asymmetric cards',
    heroLayout: 'center',
    navStyle: 'default',
    cardStyle: 'bordered',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'gallery', 'contact', 'pricing'],
  },
  {
    id: 'minimal-mono',
    name: 'Minimal Mono',
    category: 'universal',
    description: 'Ultra-minimal monochrome with single accent color',
    heroLayout: 'minimal',
    navStyle: 'hamburger',
    cardStyle: 'minimal',
    borderRadius: 'sm',
    sections: ['hero', 'about', 'services', 'contact'],
  },
  {
    id: 'showcase-pro',
    name: 'Showcase Pro',
    category: 'universal',
    description: 'Full-bleed image showcase with parallax and floating cards',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'elevated',
    borderRadius: 'md',
    sections: ['hero', 'services', 'gallery', 'testimonials', 'contact'],
  },
  {
    id: 'dashboard-sleek',
    name: 'Dashboard Sleek',
    category: 'universal',
    description: 'Modern SaaS-style layout with stats cards and clean lines',
    heroLayout: 'left',
    navStyle: 'default',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'pricing', 'faq', 'contact'],
  },
  // ============== HOSPITALITY ==============
  {
    id: 'concierge-suite',
    name: 'Concierge Suite',
    category: 'hospitality',
    description: 'Luxury hotel with room gallery, booking CTA, and amenity cards',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'gallery', 'hotel', 'contact'],
  },
  {
    id: 'skyline-hotel',
    name: 'Skyline Hotel',
    category: 'hospitality',
    description: 'City hotel with panoramic hero and roof-top imagery',
    heroLayout: 'fullscreen',
    navStyle: 'glass',
    cardStyle: 'glass',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'hotel', 'contact'],
  },
  {
    id: 'riviera-resort',
    name: 'Riviera Resort',
    category: 'hospitality',
    description: 'Beach resort with tropical palette and leisure-focused layout',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'bordered',
    borderRadius: 'xl',
    sections: ['hero', 'about', 'services', 'gallery', 'hotel', 'contact'],
  },
  {
    id: 'bnb-cozy',
    name: 'BnB Cozy',
    category: 'hospitality',
    description: 'Homey bed-and-breakfast with room tour and local guide',
    heroLayout: 'center',
    navStyle: 'minimal',
    cardStyle: 'default',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'hotel', 'gallery', 'testimonials', 'contact'],
  },
  // ============== BEAUTY / FASHION ==============
  {
    id: 'atelier-lookbook',
    name: 'Atelier Lookbook',
    category: 'beauty',
    description: 'Fashion lookbook with full-bleed imagery and runway feel',
    heroLayout: 'fullscreen',
    navStyle: 'hamburger',
    cardStyle: 'minimal',
    borderRadius: 'none',
    sections: ['hero', 'about', 'services', 'gallery', 'products', 'contact'],
  },
  {
    id: 'catwalk-reel',
    name: 'Catwalk Reel',
    category: 'beauty',
    description: 'Video-first layout with auto-playing catwalk reel hero',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'glass',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'boutique-shelf',
    name: 'Boutique Shelf',
    category: 'beauty',
    description: 'Product shelf with floating lookbook cards and try-on CTA',
    heroLayout: 'split',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'products', 'gallery', 'contact'],
  },
  {
    id: 'glam-studio',
    name: 'Glam Studio',
    category: 'beauty',
    description: 'Bold glam aesthetic with before-after gallery and service menu',
    heroLayout: 'right',
    navStyle: 'glass',
    cardStyle: 'bordered',
    borderRadius: 'full',
    sections: ['hero', 'services', 'gallery', 'products', 'contact'],
  },
  {
    id: 'spa-serene',
    name: 'Spa Serene',
    category: 'beauty',
    description: 'Calming spa layout with organic shapes and soft gradients',
    heroLayout: 'center',
    navStyle: 'minimal',
    cardStyle: 'glass',
    borderRadius: 'xl',
    sections: ['hero', 'about', 'services', 'pricing', 'contact'],
  },
  // ============== FOOD / CATERING ==============
  {
    id: 'owambe-feast',
    name: 'Owambe Feast',
    category: 'food',
    description: 'Nigerian party feast with vibrant food gallery and menu cards',
    heroLayout: 'fullscreen',
    navStyle: 'hamburger',
    cardStyle: 'elevated',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'chefs-table',
    name: 'Chef\'s Table',
    category: 'food',
    description: 'Fine dining with chef story, tasting menu, and reservation form',
    heroLayout: 'left',
    navStyle: 'minimal',
    cardStyle: 'bordered',
    borderRadius: 'none',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'streetfood-grid',
    name: 'Streetfood Grid',
    category: 'food',
    description: 'Vibrant street food vendor cards with bold typography',
    heroLayout: 'center',
    navStyle: 'default',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'gallery', 'contact'],
  },
  {
    id: 'bakery-warm',
    name: 'Bakery Warm',
    category: 'food',
    description: 'Warm bakery feel with rustic textures and product grid',
    heroLayout: 'split',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'products', 'gallery', 'contact'],
  },
  {
    id: 'cafe-corner',
    name: 'Cafe Corner',
    category: 'food',
    description: 'Cozy coffee shop with menu board style and ambient photos',
    heroLayout: 'minimal',
    navStyle: 'hamburger',
    cardStyle: 'minimal',
    borderRadius: 'sm',
    sections: ['hero', 'services', 'gallery', 'contact'],
  },
  // ============== MUSIC / ENTERTAINMENT ==============
  {
    id: 'sonic-wave',
    name: 'Sonic Wave',
    category: 'music',
    description: 'Audio-visualizer hero with track listing and gig calendar',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'glass',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'music', 'gallery', 'contact'],
  },
  {
    id: 'vinyl-stage',
    name: 'Vinyl Stage',
    category: 'music',
    description: 'Retro vinyl aesthetic with spin-animated record hero',
    heroLayout: 'split',
    navStyle: 'hamburger',
    cardStyle: 'elevated',
    borderRadius: 'full',
    sections: ['hero', 'about', 'music', 'gallery', 'contact'],
  },
  {
    id: 'studio-reel',
    name: 'Studio Reel',
    category: 'music',
    description: 'Producer studio with beat portfolio, pricing, and session booking',
    heroLayout: 'center',
    navStyle: 'default',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'about', 'music', 'services', 'contact'],
  },
  {
    id: 'dj-booth',
    name: 'DJ Booth',
    category: 'music',
    description: 'Club-style layout with dark theme, tracklist, and event calendar',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'glass',
    borderRadius: 'none',
    sections: ['hero', 'music', 'gallery', 'pricing', 'contact'],
  },
  // ============== PHOTOGRAPHY ==============
  {
    id: 'lens-portfolio',
    name: 'Lens Portfolio',
    category: 'photography',
    description: 'Minimal grid portfolio with fullscreen lightbox preview',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'minimal',
    borderRadius: 'none',
    sections: ['hero', 'gallery', 'services', 'testimonials', 'contact'],
  },
  {
    id: 'wedding-story',
    name: 'Wedding Story',
    category: 'photography',
    description: 'Romantic wedding album layout with timeline and love notes',
    heroLayout: 'split',
    navStyle: 'glass',
    cardStyle: 'bordered',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'gallery', 'pricing', 'contact'],
  },
  // ============== FITNESS ==============
  {
    id: 'iron-gym',
    name: 'Iron Gym',
    category: 'fitness',
    description: 'Bold dark gym layout with transformation grid and class schedule',
    heroLayout: 'fullscreen',
    navStyle: 'hamburger',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'pricing', 'contact'],
  },
  {
    id: 'yoga-flow',
    name: 'Yoga Flow',
    category: 'fitness',
    description: 'Calm zen-inspired layout with pastels and organic curves',
    heroLayout: 'center',
    navStyle: 'minimal',
    cardStyle: 'glass',
    borderRadius: 'xl',
    sections: ['hero', 'services', 'gallery', 'pricing', 'contact'],
  },
  // ============== EVENTS ==============
  {
    id: 'event-vogue',
    name: 'Event Vogue',
    category: 'events',
    description: 'Elegant event planning layout with portfolio and inquiry form',
    heroLayout: 'fullscreen',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'services', 'gallery', 'testimonials', 'contact'],
  },
  {
    id: 'party-zone',
    name: 'Party Zone',
    category: 'events',
    description: 'Fun vibrant party planner with photo gallery and package cards',
    heroLayout: 'split',
    navStyle: 'hamburger',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'services', 'gallery', 'pricing', 'contact'],
  },
  // ============== CONSULTING ==============
  {
    id: 'advisor-pro',
    name: 'Advisor Pro',
    category: 'consulting',
    description: 'Professional consulting layout with credentials and case studies',
    heroLayout: 'left',
    navStyle: 'default',
    cardStyle: 'minimal',
    borderRadius: 'sm',
    sections: ['hero', 'about', 'services', 'testimonials', 'contact'],
  },
  {
    id: 'coach-vault',
    name: 'Coach Vault',
    category: 'consulting',
    description: 'Life coach layout with ebook showcase and course catalog',
    heroLayout: 'center',
    navStyle: 'glass',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'pricing', 'faq', 'contact'],
  },
  // ============== MORE UNIVERSAL ==============
  {
    id: 'neon-dark',
    name: 'Neon Dark',
    category: 'universal',
    description: 'Dark mode with neon accent glows and futuristic typography',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'glass',
    borderRadius: 'lg',
    sections: ['hero', 'services', 'pricing', 'testimonials', 'contact'],
  },
  {
    id: 'pastel-dream',
    name: 'Pastel Dream',
    category: 'universal',
    description: 'Soft pastel tones with rounded shapes and playful layout',
    heroLayout: 'center',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'xl',
    sections: ['hero', 'about', 'services', 'gallery', 'testimonials', 'contact'],
  },
  {
    id: 'bold-brutalist',
    name: 'Bold Brutalist',
    category: 'universal',
    description: 'Raw brutalist design with heavy borders and monospace type',
    heroLayout: 'left',
    navStyle: 'hamburger',
    cardStyle: 'bordered',
    borderRadius: 'none',
    sections: ['hero', 'about', 'services', 'pricing', 'contact'],
  },
  {
    id: 'gradient-wave',
    name: 'Gradient Wave',
    category: 'universal',
    description: 'Flowing gradient backgrounds with wave dividers between sections',
    heroLayout: 'center',
    navStyle: 'glass',
    cardStyle: 'glass',
    borderRadius: 'xl',
    sections: ['hero', 'about', 'services', 'testimonials', 'faq', 'contact'],
  },
  {
    id: 'card-mosaic',
    name: 'Card Mosaic',
    category: 'universal',
    description: 'Masonry-style card layout for mixed content types',
    heroLayout: 'center',
    navStyle: 'default',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'gallery', 'products', 'contact'],
  },
  {
    id: 'clean-stripe',
    name: 'Clean Stripe',
    category: 'universal',
    description: 'Alternating light and dark section stripes for visual rhythm',
    heroLayout: 'left',
    navStyle: 'default',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'about', 'services', 'pricing', 'testimonials', 'contact'],
  },
  {
    id: 'split-hero',
    name: 'Split Hero',
    category: 'universal',
    description: 'Split-screen hero with image on one side, text on the other',
    heroLayout: 'split',
    navStyle: 'default',
    cardStyle: 'default',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'gallery', 'faq', 'contact'],
  },
  {
    id: 'studio-one',
    name: 'Studio One',
    category: 'universal',
    description: 'Single-column editorial with bold typography and clean sections',
    heroLayout: 'minimal',
    navStyle: 'minimal',
    cardStyle: 'minimal',
    borderRadius: 'none',
    sections: ['hero', 'about', 'services', 'testimonials', 'contact'],
  },
  // ============== NIGERIAN SPECIAL ==============
  {
    id: 'owambe-gold',
    name: 'Owambe Gold',
    category: 'events',
    description: 'Gold-themed Nigerian party planner with RSVP and menu display',
    heroLayout: 'fullscreen',
    navStyle: 'transparent',
    cardStyle: 'elevated',
    borderRadius: 'lg',
    sections: ['hero', 'about', 'services', 'pricing', 'gallery', 'testimonials', 'contact'],
  },
  {
    id: 'lagos-hustle',
    name: 'Lagos Hustle',
    category: 'universal',
    description: 'Fast-paced urban layout with bold CTAs and product showcase',
    heroLayout: 'center',
    navStyle: 'hamburger',
    cardStyle: 'bordered',
    borderRadius: 'md',
    sections: ['hero', 'services', 'products', 'gallery', 'contact'],
  },
]

export const TEMPLATE_CATEGORIES: { id: TemplateCategory; label: string; icon: string }[] = [
  { id: 'universal', label: 'Universal', icon: 'LayoutGrid' },
  { id: 'hospitality', label: 'Hospitality / Hotelia', icon: 'Hotel' },
  { id: 'beauty', label: 'Beauty / Fashion', icon: 'Sparkles' },
  { id: 'food', label: 'Food / Catering', icon: 'UtensilsCrossed' },
  { id: 'music', label: 'Music / Entertainment', icon: 'Music' },
  { id: 'photography', label: 'Photography', icon: 'Camera' },
  { id: 'fitness', label: 'Fitness / Wellness', icon: 'Dumbbell' },
  { id: 'events', label: 'Events / Planning', icon: 'PartyPopper' },
  { id: 'consulting', label: 'Consulting / Coaching', icon: 'Briefcase' },
]

export const DEFAULT_TEMPLATE = TEMPLATES[0]

export function getTemplateById(id: string): TemplateConfig | undefined {
  return TEMPLATES.find(t => t.id === id)
}

export function getTemplatesByCategory(category: TemplateCategory): TemplateConfig[] {
  return TEMPLATES.filter(t => t.category === category)
}
